# Generated by Django 5.0.7 on 2024-08-11 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 12, 2, 59, 46, 292334))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 8, 12, 2, 59, 46, 292334))),
            ],
        ),
    ]
